Models/AlumnoModel.cs
namespace MVCCapas2025.Models
{
    public class AlumnoModel
    {
        public int AlumnoID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string CorreoElectronico { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MVCCapas2025.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProfesorModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCCapas2025.Models
{
    public class ProfesorModel
    {
        public int ProfesorID { get; set; }
        [Required]
        [MaxLength(50)]
        public string Nombre { get; set; }
        [Required]
        [MaxLength(50)]
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        [EmailAddress]
        public string CorreoElectronico { get; set; }
    }
}

Controllers/AlumnoController.cs
using Domain;
using Infraestructure;
using Microsoft.AspNetCore.Mvc;
using MVCCapas2025.Models;
using Services;

namespace MVCCapas2025.Controllers
{
    public class AlumnoController : Controller
    {
        public IActionResult Index()
        {
            AlumnoServices service = new AlumnoServices();

            var alumnos = service.Get();


            var model = alumnos.Select(x => new AlumnoModel
            {
                AlumnoID = x.AlumnoID,
                Nombre = x.Nombre,
                Apellido = x.Apellido,
                FechaNacimiento = x.FechaNacimiento,
                CorreoElectronico = x.CorreoElectronico
            }).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Nombre, Apellido, FechaNacimiento, CorreoElectronico")] AlumnoModel model)
        {

            if (ModelState.IsValid)
            {
                AlumnoServices service = new AlumnoServices();
                var dominio = new Alumno
                {
                    Nombre = model.Nombre,
                    Apellido = model.Apellido,
                    FechaNacimiento = model.FechaNacimiento,
                    CorreoElectronico = model.CorreoElectronico,
                    Estado = true
                };
                service.Insert(dominio);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            AlumnoServices service = new AlumnoServices();
            var alumno = service.BuscarPorID(id);
            var dominio = new AlumnoModel
            {
                AlumnoID = alumno.AlumnoID,
                Nombre = alumno.Nombre,
                Apellido = alumno.Apellido,
                FechaNacimiento = alumno.FechaNacimiento,
                CorreoElectronico = alumno.CorreoElectronico
            };
            return View(dominio);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            AlumnoServices service = new AlumnoServices();
            service.DeleteLogic(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCCapas2025.Models;
using System.Diagnostics;

namespace MVCCapas2025.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProfesoresController.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using MVCCapas2025.Models;
using Services;

namespace MVCCapas2025.Controllers
{
    public class ProfesoresController : Controller
    {
        public IActionResult Index()
        {
            ProfesorServices service = new ProfesorServices();

            var profesors = service.Get();


            var model = profesors.Select(x => new ProfesorModel
            {
                ProfesorID = x.ProfesorID,
                Nombre = x.Nombre,
                Apellido = x.Apellido,
                Especialidad = x.Especialidad,
                CorreoElectronico = x.CorreoElectronico
            }).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Nombre, Apellido, Especialidad, CorreoElectronico")] ProfesorModel model)
        {

            if (ModelState.IsValid)
            {
                ProfesorServices service = new ProfesorServices();
                var dominio = new Profesor
                {
                    Nombre = model.Nombre,
                    Apellido = model.Apellido,
                    Especialidad = model.Especialidad,
                    CorreoElectronico = model.CorreoElectronico,
                    Estado = true
                };
                service.Insert(dominio);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ProfesorServices service = new ProfesorServices();
            var profesor = service.BuscarPorID(id);
            var dominio = new ProfesorModel
            {
                ProfesorID = profesor.ProfesorID,
                Nombre = profesor.Nombre,
                Apellido = profesor.Apellido,
                Especialidad = profesor.Especialidad,
                CorreoElectronico = profesor.CorreoElectronico
            };
            return View(dominio);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            ProfesorServices service = new ProfesorServices();
            service.DeleteLogic(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Alumno/Create.cshtml
@model MVCCapas2025.Models.AlumnoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AlumnoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Alumno/Delete.cshtml
@model MVCCapas2025.Models.AlumnoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AlumnoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlumnoID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlumnoID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Alumno/Index.cshtml
@model IEnumerable<MVCCapas2025.Models.AlumnoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlumnoID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlumnoID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.AlumnoID })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Profesores/Create.cshtml
@model MVCCapas2025.Models.ProfesorModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProfesorModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Especialidad" class="control-label"></label>
                <input asp-for="Especialidad" class="form-control" />
                <span asp-validation-for="Especialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Profesores/Delete.cshtml
@model MVCCapas2025.Models.ProfesorModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProfesorModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfesorID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfesorID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Profesores/Index.cshtml
@model IEnumerable<MVCCapas2025.Models.ProfesorModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProfesorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProfesorID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProfesorID })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCapas2025</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCCapas2025.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCapas2025</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="Index">Alumnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profesores" asp-action="Index">Profesores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVCCapas2025 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>